# Generated by Django 4.0 on 2021-12-29 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.portfoliogroup'),
        ),
    ]
